### ISSUE TITLE
Doesn't install on OSX El Capitan

### ISSUE THREAD

**Issue by pettai** [Yubico/yubikey-neo-manager#39] opened 2015-07-04 22:59 UTC
Installation ends with the message:
"The Installation Failed.
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance"

PCSC framework should be there (like Yosemite's), so hopefully it should be a trivial fix... 
http://ludovicrousseau.blogspot.se/2015/06/pcsc-framework-will-stay-in-mac-os-x.html

**Comment by lfaraone** [comment] 2015-08-02 05:41
Seems to come down to this failed operation:


``` .pytb
Traceback (most recent call last):
File "/tmp/PKInstallSandbox.VfHvCx/Scripts/com.yubico.pkg.YubiKeyNEOManager.4QNnt8/postinstall", line 71, in <module>
    main()
  File "/tmp/PKInstallSandbox.VfHvCx/Scripts/com.yubico.pkg.YubiKeyNEOManager.4QNnt8/postinstall", line 62, in main
    with open(FNAME, 'w') as f:
IOError: [Errno 1] Operation not permitted: '/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist'
```

... which I assume is related to the security enhancements provided in El Capitan. See also the [full install log](https://gist.github.com/lfaraone/433d1c75019d06208136).

**Comment by dainnilsson** [comment] 2015-08-03 11:30
Thanks for the installation log! Indeed this does look like it's caused by the "System Integrity Protection" in El Capitan. I'm not sure if there is a way to work around it, or if the patch will have to just fail silently on this error and leave the CCID configuration unpatched.

**Comment by dainnilsson** [comment] 2015-08-03 13:24
A workaround is booting into recovery and unchecking **Enforce System Integrity Protection** from the **Utilities > Security Configuration** and then running the installer, which allows it to install and patch the file. Once the file is patched you can re-enable System Integrity Protection. I believe this should work, but have not tested it.

**Comment by dainnilsson** [comment] 2015-11-05 14:20
Closing as this should be working now.

**Closed by dainnilsson** 2015-11-05 14:20 UTC
